### ISSUE TITLE
make quotes visible somewhere

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#135]
so far we have:

---

> Just now visiting open-wc.org site for the first time. U guys are killing it! Amazing stuff, and IMO totally on target. many thanks

petecarapetyan

---

> I used open-wc to get testing working, was sooo helpful, works like a charm

Ikira

**Comment by daKmoR** [comment]
sounds good 👍

**Comment by erikkroes** [comment]
I would add them to the frontpage. This makes them one of the first things people will see and it creates a feeling of trust. The earlier the better.

**Comment by daKmoR** [comment]
@thepassle any idea how we could add them to the front page? or somewhere more prominent?

**Comment by thepassle** [comment]
We could add them here maybe?

some better styling ofc
<img width="1280" alt="screen shot 2019-01-30 at 22 52 18" src="https://user-images.githubusercontent.com/17054057/52015208-c69e1080-24e1-11e9-9bec-f83cc7873167.png">

**Comment by daKmoR** [comment]
place looks good to me 👍 

however, I'm not sure how easy it will be to make that happen - might require diving a little more into vuepress and adopting one of their components/templates or adjust the theme 🙈

**Comment by thepassle** [comment]
in `docs/README.md` you can just add html:

```
---
home: true
heroImage: /hero.png
actionText: Get Started →
actionLink: /guide/
features:
- title: Smart Defaults
  details: Enjoy the peace of mind that comes from having a well-known default solution for almost everything. From linting to testing to demos to publishing - have the full experience.
- title: Awesome Generators
  details: Get up and running quickly with opinionated generators, or add recommended tools to existing projects. Our comprehensive fleet of generators have got you covered.
- title: Open Source Love
  details: Open Web Components is a community-effort, independent of any framework or company. We use mostly open-source tools and services. 
footer: MIT Licensed | Copyright © 2018-present open-wc
---
<p align="center" style="margin: 40px;">
	I used open-wc to get testing working, was sooo helpful, works like a charm
</p>
```

Alternatively we can add a `components/` folder to `docs/.vuepress/components/` and use a Vue component instead. But we might as well just write the html in that case
