### ISSUE TITLE
[docs] home page feature sections are squished on mobile

### ISSUE THREAD

**Issue by anoblet** [open-wc/open-wc#995]
On the home page, when browsing on mobile the feature sections seem squished. This could be fixed by either reducing or getting rid of the padding.

```css
@media (max-width: 719px)
.home .feature {
    max-width: 100%;
    padding: 0 2.5rem; /* This should be decreased */
}
```
